/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IERC721Registry {
  export type TokenInfoStruct = { source: string; clone: string };

  export type TokenInfoStructOutput = [string, string] & {
    source: string;
    clone: string;
  };
}

export interface IERC721RegistryInterface extends utils.Interface {
  contractName: "IERC721Registry";
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "CONFIGURATOR_ROLE()": FunctionFragment;
    "containsKey(bytes32)": FunctionFragment;
    "createToken(address,bytes32,string,string,string,uint256,address,address)": FunctionFragment;
    "getTokenAddresses()": FunctionFragment;
    "keys()": FunctionFragment;
    "sources(address)": FunctionFragment;
    "tokens(bytes32)": FunctionFragment;
    "updateSources(address[],bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIGURATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "containsKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [
      string,
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "keys", values?: undefined): string;
  encodeFunctionData(functionFragment: "sources", values: [string]): string;
  encodeFunctionData(functionFragment: "tokens", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "updateSources",
    values: [string[], boolean]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CONFIGURATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "containsKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sources", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSources",
    data: BytesLike
  ): Result;

  events: {
    "SourceChanged(address,bool)": EventFragment;
    "TokenCreated(address,address,uint256,bytes32,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SourceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenCreated"): EventFragment;
}

export type SourceChangedEvent = TypedEvent<
  [string, boolean],
  { source: string; added: boolean }
>;

export type SourceChangedEventFilter = TypedEventFilter<SourceChangedEvent>;

export type TokenCreatedEvent = TypedEvent<
  [string, string, BigNumber, string, string, string],
  {
    clone: string;
    source: string;
    maxCap: BigNumber;
    key: string;
    name: string;
    symbol: string;
  }
>;

export type TokenCreatedEventFilter = TypedEventFilter<TokenCreatedEvent>;

export interface IERC721Registry extends BaseContract {
  contractName: "IERC721Registry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC721RegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    CONFIGURATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    containsKey(key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    createToken(
      source: string,
      key: BytesLike,
      name: string,
      symbol: string,
      baseUri: string,
      maxCap: BigNumberish,
      admin: string,
      minter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTokenAddresses(
      overrides?: CallOverrides
    ): Promise<[string[]] & { addresses: string[] }>;

    keys(overrides?: CallOverrides): Promise<[string[]]>;

    sources(source: string, overrides?: CallOverrides): Promise<[boolean]>;

    tokens(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[IERC721Registry.TokenInfoStructOutput]>;

    updateSources(
      newSources: string[],
      add: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  CONFIGURATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  containsKey(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  createToken(
    source: string,
    key: BytesLike,
    name: string,
    symbol: string,
    baseUri: string,
    maxCap: BigNumberish,
    admin: string,
    minter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTokenAddresses(overrides?: CallOverrides): Promise<string[]>;

  keys(overrides?: CallOverrides): Promise<string[]>;

  sources(source: string, overrides?: CallOverrides): Promise<boolean>;

  tokens(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<IERC721Registry.TokenInfoStructOutput>;

  updateSources(
    newSources: string[],
    add: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    CONFIGURATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    containsKey(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    createToken(
      source: string,
      key: BytesLike,
      name: string,
      symbol: string,
      baseUri: string,
      maxCap: BigNumberish,
      admin: string,
      minter: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getTokenAddresses(overrides?: CallOverrides): Promise<string[]>;

    keys(overrides?: CallOverrides): Promise<string[]>;

    sources(source: string, overrides?: CallOverrides): Promise<boolean>;

    tokens(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<IERC721Registry.TokenInfoStructOutput>;

    updateSources(
      newSources: string[],
      add: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SourceChanged(address,bool)"(
      source?: string | null,
      added?: null
    ): SourceChangedEventFilter;
    SourceChanged(
      source?: string | null,
      added?: null
    ): SourceChangedEventFilter;

    "TokenCreated(address,address,uint256,bytes32,string,string)"(
      clone?: string | null,
      source?: string | null,
      maxCap?: null,
      key?: null,
      name?: null,
      symbol?: null
    ): TokenCreatedEventFilter;
    TokenCreated(
      clone?: string | null,
      source?: string | null,
      maxCap?: null,
      key?: null,
      name?: null,
      symbol?: null
    ): TokenCreatedEventFilter;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    CONFIGURATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    containsKey(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    createToken(
      source: string,
      key: BytesLike,
      name: string,
      symbol: string,
      baseUri: string,
      maxCap: BigNumberish,
      admin: string,
      minter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTokenAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    keys(overrides?: CallOverrides): Promise<BigNumber>;

    sources(source: string, overrides?: CallOverrides): Promise<BigNumber>;

    tokens(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    updateSources(
      newSources: string[],
      add: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONFIGURATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    containsKey(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createToken(
      source: string,
      key: BytesLike,
      name: string,
      symbol: string,
      baseUri: string,
      maxCap: BigNumberish,
      admin: string,
      minter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTokenAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keys(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sources(
      source: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokens(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateSources(
      newSources: string[],
      add: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
